"""add_missing_indexes

Revision ID: cd4875d88547
Revises: 2f45c668549b
Create Date: 2026-05-02 23:21:47.020737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4875d88547'
down_revision = '2f45c668549b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_join_requests', schema=None) as batch_op:
        batch_op.create_index('ix_gjr_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_gm_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_user_read', ['user_id', 'read'], unique=False)

    with op.batch_alter_table('user_question_progress', schema=None) as batch_op:
        batch_op.create_index('ix_uqp_question_solved', ['question_id', 'solved'], unique=False)
        batch_op.create_index('ix_uqp_user_solved', ['user_id', 'solved'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_question_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_uqp_user_solved')
        batch_op.drop_index('ix_uqp_question_solved')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_user_read')

    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_gm_user_id')

    with op.batch_alter_table('group_join_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_gjr_user_status')

    # ### end Alembic commands ###
